/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_VentanaArticulo;

/**
 *
 * @author 3rika
 */
public class Panel_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Informacion
     */
    Controlador_VentanaArticulo controladorArticulo;
    
    public Panel_Informacion() {
        initComponents();
        deshabilitarCampos();
    }
    
    public void agregarEventos(Controlador_VentanaArticulo controladorVentana)
    {
        this.controladorArticulo = controladorVentana;
        this.btn_Buscar.addActionListener(controladorVentana);
        this.jt_NCodigo.addActionListener(controladorVentana);
    }
    
    public String[] devolverInformacion()
    {
        String informacion[]=new String[3];
        informacion[0] = this.jt_NCodigo.getText();
        informacion[1] = this.jt_Articulo.getText();
        informacion[2] = this.jt_Cantidad.getText();
        
        return informacion;
    }
    
    public String devolverCodigo()
    {
        return this.jt_NCodigo.getText();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_Articulo.setText(arreglo[0]);
        this.jt_Cantidad.setText(arreglo[1]);
    }
    
    public void habilitarCampos()
    {
        this.jt_Articulo.setEnabled(true);
        this.jt_Cantidad.setEnabled(true);
    }
    
    public void deshabilitarCampos()
    {
        this.jt_NCodigo.setEnabled(true);
        this.jt_NCodigo.setText("");
        this.jt_Articulo.setEnabled(false);
        this.jt_Articulo.setText("");
        this.jt_Cantidad.setEnabled(false);
        this.jt_Cantidad.setText("");
    }
    public void habilitarEdicion()
    {
        this.jt_NCodigo.setEnabled(false);
        this.jt_Articulo.setEnabled(true);
        this.jt_Cantidad.setEnabled(true);
    }
    public void mostrarInformacionRegistro(String informacion)
    {
        this.jTextArea1.setText(informacion);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Codigo = new javax.swing.JLabel();
        jl_Articulo = new javax.swing.JLabel();
        jl_Cantidad = new javax.swing.JLabel();
        jt_NCodigo = new javax.swing.JTextField();
        jt_Articulo = new javax.swing.JTextField();
        jt_Cantidad = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jl_Codigo.setText("N.Codigo");

        jl_Articulo.setText("Articulo");

        jl_Cantidad.setText("Cantidad");

        jt_NCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NCodigoKeyPressed(evt);
            }
        });

        btn_Buscar.setText("BUSCAR");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N.Codigo", "Articulo", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_Cantidad)
                                .addGap(18, 18, 18)
                                .addComponent(jt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Codigo)
                                    .addComponent(jl_Articulo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_NCodigo)
                                    .addComponent(jt_Articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addComponent(btn_Buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Codigo)
                    .addComponent(jt_NCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Articulo)
                    .addComponent(jt_Articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cantidad)
                    .addComponent(jt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10)
        {
            this.controladorArticulo.buscar();
        }
    }//GEN-LAST:event_jt_NCodigoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jl_Articulo;
    private javax.swing.JLabel jl_Cantidad;
    private javax.swing.JLabel jl_Codigo;
    private javax.swing.JTextField jt_Articulo;
    private javax.swing.JTextField jt_Cantidad;
    private javax.swing.JTextField jt_NCodigo;
    // End of variables declaration//GEN-END:variables
}
